cleaning code

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -5,6 +5,7 @@ IFS=$'\n\t'
 trap ctrl_c 2
 ctrl_c(){ printf "$Y\n\n   [¿] Need a help [?]$B\nTelegram : t.me/Ivam3_Bot$W\n\n";exit;}
 GIT="https://raw.githubusercontent.com/ivam3"
+APKTOOL="https://github.com/iBotPeaches/Apktool/releases/download/v2.6.0/apktool_2.6.0.jar"
 R='\033[1;31m'
 G='\033[1;32m'
 Y='\033[1;33m'
@@ -16,7 +17,7 @@ command -v curl >/dev/null || yes|apt install curl >/dev/null 2>&1
 curl -LS https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/libexec/banner/IbyC|bash
 instajava() {
 	printf "$G(_>)─➤$W Installing JAVA_[it could take a while]\n"
-	git clone https://github.com/ivam3/java.git $PREFIX/share/java >/dev/null 2>&1
+	git clone --quiet https://github.com/ivam3/java.git $PREFIX/share/java >/dev/null 2>&1
 	if [ -d $PREFIX/share/java ]; then
 		cd $PREFIX/share/java
 		chmod -R 711 $PREFIX/share/java
@@ -27,30 +28,35 @@ instajava() {
 		ctrl_c
 	fi
 }
+
 #:::: MSF ::::#
-! command -v msfconsole || { echo >&2 "$R\n(_>)─➤$W Metasploit isn't in PATH. Install it. Aborting."; exit 1; }
+! command -v msfconsole || { printf >&2 "$R\n(_>)─➤$W Metasploit isn't in PATH. Install it. Aborting."; exit 1; }
 
 printf "$G(_>)─➤$W Upgrading Termux.\n"
 yes|pkg update && pkg upgrade
-for repo in git wget curl axel tar aapt;do
-	command -v $repo >/dev/null || yes|apt install $repo >/dev/null 2>&1
+printf "$G(_>)─➤$W Installing dependencies.\n"
+for repo in git wget curl axel tar aapt apksigner openjdk-17;do
+	command -v $repo >/dev/null || yes|apt install $repo >/dev/null 2>/dev/null
 done
+[[ -d $PREFIX/var/spool ]] || mkdir -p $PREFIX/var/spool
+wget -q $APKTOOL -O $PREFIX/var/spool/apktool.jar
+cat <<- CONF > $PREFIX/bin/apktool
+#!/usr/bin/bash
+exec \$PREFIX/bin/java -jar \$PREFIX/var/spool/apktool.jar  "\$@"
+CONF
+chmod 751 $PREFIX/bin/apktool
 
 #:::: fixArgX ::::#
 printf "$Y\n(_>)─➤$W Fixing argument '-x' in metasploit.$W\n"
-if [ ! -d ~/.android ]; then
-	mkdir ~/.android
-fi
-if [ ! -d $PREFIX/opt/metasploit-framework/lib/msf/core/payload ];then
-	mkdir -p $PREFIX/opt/metasploit-framework/lib/msf/core/payload
-fi
+[[ -d ~/.android ]] || mkdir ~/.android
+[[ -d $PREFIX/opt/metasploit-framework/lib/msf/core/payload ]] || mkdir -p $PREFIX/opt/metasploit-framework/lib/msf/core/payload
 
 printf "$Y\n(_>)─➤$W Downloading an android keystore.$W\n"
 wget -q $GIT/java/master/.embed/apk.rb -O $PREFIX/opt/metasploit-framework/lib/msf/core/payload/apk.rb
 wget -q $GIT/embed/master/.IbyC/debug.keystore -O ~/.android/debug.keystore -q
 
 printf "$Y\n(_>)─➤$W Installing ruby gems."
-rubyVer=$(ruby -v | awk -F " " '{print $2}'|awk -F "." '{print $1}')
+rubyVer=$(ruby -v|awk -F " " '{print $2}'|awk -F "." '{print $1}')
 command -v ruby > /dev/null 2>&1 || apt install ruby -y > /dev/null 2>&1
 if [ "$rubyVer" != "2" ];then
 	wget -q https://raw.githubusercontent.com/ivam3/i-Haklab/master/.set/bin/IbyC-fixer -O $PREFIX/bin/IbyC-fixer;chmod +x $PREFIX/bin/IbyC-fixer
@@ -60,20 +66,21 @@ command -v bundle > /dev/null || gem install bundle > /dev/null 2>&1
 bundle install
 
 #:::: JAVA ::::#
-if ! command -v java
+java=$(apt search openjdk-17 2>/dev/null|grep -oE openjdk)
+if ! -z $java #! command -v java
 then
 	printf "$Y(_>)─➤$W JAVA already exist$Y |$W Do you want re-install it?\n"
 	while read -p "(yes/no)─➤ " yesorno && [ -z $yesorno ]; do
 		continue
 	done
 	if [ $yesorno = "yes" ] || [ $yesorno = "Yes" ] || [ $yesorno = "YES" ];then
-		instajava
+		yes|apt reinstall openjdk-17 -y #instajava
 	else
 		printf "$G\n(_>)─➤$W JAVA keeped!!"
 		sleep 1
 	fi
 else
-	instajava
+	pkg install openjdk-17 -y #instajava
 fi
 printf "$Y\n(_>)-> ::::::::::::::: DONE !! :::::::::::::::: <-(<_)$G\n\tTo fix issues going to$B t.me/Ivam3_Bot$W\n"
 #						@Ivam3.
